<?php
include 'top.php';
$text = <<<TEXT
 <div class="text">
   <h2>Contents</h2>
    <h2><a href="../eohan/main.php">Main page</a></h2>
    <h3>Readings</h3>
    <p>All possible syllables of Chinese (Mandarin and Cantonese) and
      Sino-Japanese, Sino-Korean and Sino-Vietnamese with links to the
      characters used to write them.</p>
    <h3>Characters by radical</h3>
    <p>A radical and strokes index to the site.</p>
    <h3>Search</h3>
    <p>Input a character to go to its page.</p>
    <h3>Sources</h3>
    <p>The historical texts from which this site was autogenerated, with
      reconstructed pronunciations and links from each character to its page.<br>
    </p>
    <h3>Zhongyuan Yinyun</h3>
    <p>A dictionary of Early Mandarin from around 1200 AD.<br>
    </p>
    <h3>Yunjing</h3>
    <p>A rhyme table from around 800 AD giving the pronunciation of each
      possible syllable of Late Middle Chinese and a single character having
      that pronunciation. The columns represent the initial consonants of each
      syllable and the rows represent the ending, tone and other information.<br>
    </p>
    <h3>Guangyun</h3>
    <p>A dictionary of Early Middle Chinese from around 600 AD. The sections
      list all characters having a given pronunciation and the sections are
      grouped by ending and tone. Gives the pronunciation of each character in
      terms of two others.<br>
    </p>
    <h3>Shijing</h3>
    <p>The oldest book of Chinese poetry, written at various dates between 1000
      BC and 500 BC, the Old Chinese period. Important because the lines of the
      odes rhyme with each other.<br>
    </p>
    <h3>Grammata Serica Recensa</h3>
    <p><br>
      A modern dictionary by Bernard Karlgren of characters grouped into
      phonetic series, demonstrating the phonetic information which can be
      derived from the internal structure of the characters.</p>
    <h2><a href="../eohan/glyph/U+4EBA">Character pages</a></h2>
    <h3>Dialects</h3>
    <p>The Mandarin and Cantonese pronunciations of the character.</p>
    <h3>Sinoxenic</h3>
    <p>The pronunciation of the characters as a loanword in Japanese, Korean and
      Vietnamese.</p>
    <h3>Graphic</h3>
    <p>The radical and strokes and four corner code for the character (these are
      dictionary lookup methods). The phonetic group to which Karlgren and
      Wieger assign the character.</p>
    <h3>Sources</h3>
    <p>Concordances of the character in the sources texts, Zhongyuan Yinyun,
      Yunjing, Guangyun, Shijing and Grammata Serica Recensa.</p>
    <p>Reconstructed pronunciations at different stages in the development of
      Chinese pronunciation in the systems of Edwin Pulleyblank, William Baxter
      and Bernard Karlgren.</p>
    <p><br>
    </p>
TEXT;
echo $text; 
include 'bottom.php';
?>