<!doctype html>
<!-- html5 -->
<html>
<head>
<link rel="stylesheet" type="text/css" href="../../eohan/css/general.css"></link>

<link rel="stylesheet" type="text/css" href="../../css/HuangshanSunrise.jpg"></link>

<meta content="text/html" charset="utf8" http-equiv="content-type">
<title>Eohan</title>
</head>
<body>
 <div class="wrapper">
  <div class="header">
   <a href="../../eohan/main">
   <h1 id="sitetitle">Eohan</h1>
   <h3 id="sitesubtitle">Chinese historical phonology autogenerated</h3>
   </a>
  </div>
 <div class="centre">
  <div class="left">
   <p></p>
   <table>
   <tr>
   <td>
   <a id="sitelink" href = "../..">Philip Neal</a>
   </td>
   </tr>
   <tr>
   <td>
   <a id="sitelink" href="../../eohan/main">Eohan</a>
   </td>
   </tr>
   <tr>
   <td>
   <a id="sitelink" href="../../eohan/contents">Contents</a>
   </td>
   </tr>
   <tr>
   <td>
   <a id="sitelink" href="../../eohan/about">FAQs</a>
   </td>
   </tr>
   </table>
  </div>
  <div class="right">
  </div>
  <div class="main"><div id="readings">
<h2>
Readings
</h2>

<table id="readings">
 <tr>
  <td>
  Mandarin
  </td>
  <td>
   <table>
    <tr>
     <td><a href = "../eohan/mandarininitial/A">A</a></td><td><a href = "../eohan/mandarininitial/B">B</a></td><td><a href = "../eohan/mandarininitial/C">C</a></td><td><a href = "../eohan/mandarininitial/D">D</a></td><td><a href = "../eohan/mandarininitial/E">E</a></td><td><a href = "../eohan/mandarininitial/F">F</a></td><td><a href = "../eohan/mandarininitial/G">G</a></td><td><a href = "../eohan/mandarininitial/H">H</a></td><td><a href = "../eohan/mandarininitial/J">J</a></td><td><a href = "../eohan/mandarininitial/K">K</a></td><td><a href = "../eohan/mandarininitial/L">L</a></td><td><a href = "../eohan/mandarininitial/M">M</a></td><td><a href = "../eohan/mandarininitial/N">N</a></td><td><a href = "../eohan/mandarininitial/O">O</a></td><td><a href = "../eohan/mandarininitial/P">P</a></td><td><a href = "../eohan/mandarininitial/Q">Q</a></td><td><a href = "../eohan/mandarininitial/R">R</a></td><td><a href = "../eohan/mandarininitial/S">S</a></td><td><a href = "../eohan/mandarininitial/T">T</a></td><td><a href = "../eohan/mandarininitial/W">W</a></td><td><a href = "../eohan/mandarininitial/X">X</a></td><td><a href = "../eohan/mandarininitial/Y">Y</a></td><td><a href = "../eohan/mandarininitial/Z">Z</a></td>
    </tr>
   </table>
  </td>
 </tr>
 <tr>
  <td>
  Cantonese
  </td>
  <td>
   <table>
    <tr>
     <td><a href = "../eohan/cantoneseinitial/A">A</a></td><td><a href = "../eohan/cantoneseinitial/B">B</a></td><td><a href = "../eohan/cantoneseinitial/C">C</a></td><td><a href = "../eohan/cantoneseinitial/D">D</a></td><td><a href = "../eohan/cantoneseinitial/E">E</a></td><td><a href = "../eohan/cantoneseinitial/F">F</a></td><td><a href = "../eohan/cantoneseinitial/G">G</a></td><td><a href = "../eohan/cantoneseinitial/H">H</a></td><td><a href = "../eohan/cantoneseinitial/J">J</a></td><td><a href = "../eohan/cantoneseinitial/K">K</a></td><td><a href = "../eohan/cantoneseinitial/L">L</a></td><td><a href = "../eohan/cantoneseinitial/M">M</a></td><td><a href = "../eohan/cantoneseinitial/N">N</a></td><td><a href = "../eohan/cantoneseinitial/O">O</a></td><td><a href = "../eohan/cantoneseinitial/P">P</a></td><td><a href = "../eohan/cantoneseinitial/S">S</a></td><td><a href = "../eohan/cantoneseinitial/T">T</a></td><td><a href = "../eohan/cantoneseinitial/U">U</a></td><td><a href = "../eohan/cantoneseinitial/W">W</a></td><td><a href = "../eohan/cantoneseinitial/Z">Z</a></td></tr><tr>
    </tr>
   </table>
  </td>
 </tr>
 <tr>
  <td>
  Japanese
  </td>
  <td>
   <table>
    <tr>
     <td><a href = "../eohan/japaneseinitial/A">A</a></td><td><a href = "../eohan/japaneseinitial/B">B</a></td><td><a href = "../eohan/japaneseinitial/C">C</a></td><td><a href = "../eohan/japaneseinitial/D">D</a></td><td><a href = "../eohan/japaneseinitial/E">E</a></td><td><a href = "../eohan/japaneseinitial/F">F</a></td><td><a href = "../eohan/japaneseinitial/G">G</a></td><td><a href = "../eohan/japaneseinitial/H">H</a></td><td><a href = "../eohan/japaneseinitial/I">I</a></td><td><a href = "../eohan/japaneseinitial/J">J</a></td><td><a href = "../eohan/japaneseinitial/K">K</a></td><td><a href = "../eohan/japaneseinitial/M">M</a></td><td><a href = "../eohan/japaneseinitial/N">N</a></td><td><a href = "../eohan/japaneseinitial/O">O</a></td><td><a href = "../eohan/japaneseinitial/R">R</a></td><td><a href = "../eohan/japaneseinitial/S">S</a></td><td><a href = "../eohan/japaneseinitial/T">T</a></td><td><a href = "../eohan/japaneseinitial/U">U</a></td><td><a href = "../eohan/japaneseinitial/W">W</a></td><td><a href = "../eohan/japaneseinitial/Y">Y</a></td><td><a href = "../eohan/japaneseinitial/Z">Z</a></td>
    </tr>
   </table>
  </td>
 </tr>
 <tr>
  <td>
  Korean
  </td>
  <td>
   <table>
    <tr>
     <td><a href = "../eohan/koreaninitial/A">A</a></td><td><a href = "../eohan/koreaninitial/C">C</a></td><td><a href = "../eohan/koreaninitial/E">E</a></td><td><a href = "../eohan/koreaninitial/H">H</a></td><td><a href = "../eohan/koreaninitial/I">I</a></td><td><a href = "../eohan/koreaninitial/K">K</a></td><td><a href = "../eohan/koreaninitial/L">L</a></td><td><a href = "../eohan/koreaninitial/M">M</a></td><td><a href = "../eohan/koreaninitial/N">N</a></td><td><a href = "../eohan/koreaninitial/O">O</a></td><td><a href = "../eohan/koreaninitial/P">P</a></td><td><a href = "../eohan/koreaninitial/S">S</a></td><td><a href = "../eohan/koreaninitial/T">T</a></td><td><a href = "../eohan/koreaninitial/U">U</a></td><td><a href = "../eohan/koreaninitial/W">W</a></td><td><a href = "../eohan/koreaninitial/Y">Y</a></td><tr>
    </tr>
   </table>
  </td>
 </tr>
 <tr>
  <td>
  Vietnamese
  </td>
  <td>
   <table>
    <tr>
     <td><a href = "../eohan/vietnameseinitial/A">A</a></td><td><a href = "../eohan/vietnameseinitial/B">B</a></td><td><a href = "../eohan/vietnameseinitial/C">C</a></td><td><a href = "../eohan/vietnameseinitial/D">D</a></td><td><a href = "../eohan/vietnameseinitial/Đ">Đ</a></td><td><a href = "../eohan/vietnameseinitial/E">E</a></td><td><a href = "../eohan/vietnameseinitial/G">G</a></td><td><a href = "../eohan/vietnameseinitial/H">H</a></td><td><a href = "../eohan/vietnameseinitial/I">I</a></td><td><a href = "../eohan/vietnameseinitial/K">K</a></td><td><a href = "../eohan/vietnameseinitial/L">L</a></td><td><a href = "../eohan/vietnameseinitial/M">M</a></td><td><a href = "../eohan/vietnameseinitial/N">N</a></td><td><a href = "../eohan/vietnameseinitial/O">O</a></td><td><a href = "../eohan/vietnameseinitial/P">P</a></td><td><a href = "../eohan/vietnameseinitial/Q">Q</a></td><td><a href = "../eohan/vietnameseinitial/R">R</a></td><td><a href = "../eohan/vietnameseinitial/S">S</a></td><td><a href = "../eohan/vietnameseinitial/T">T</a></td><td><a href = "../eohan/vietnameseinitial/U">U</a></td><td><a href = "../eohan/vietnameseinitial/V">V</a></td><td><a href = "../eohan/vietnameseinitial/X">X</a></td><td><a href = "../eohan/vietnameseinitial/Y">Y</a></td>
    </tr>
   </table>
  </td>
 </tr>
</table>

<h2>Characters by Radical</h2>
<p><a href = "../eohan/radicallist">List of Radicals</a></p>

<h2>Character Search</h2>
    <form  method="post" action="search.php?go"  id="searchform"> 
	      <input  type="text" name="glyph"> 
	      <input  type="submit" name="submit" value="Search"> 
	</form> 

</div>

<div id="sources">
<h2>Sources</h2>
<table id="sources">
<tr><th class="dataheader">Zhongyuan</th>
    <th class="dataheader">Yunjing</th>
    <th class="dataheader" colspan=4>Guangyun</th>
    <th></th>
    <th class="dataheader" >Shijing</th>
    <th class="dataheader">Grammata</th>
</tr>
<tr><th class="dataheader">Yinyun</th>
    <th class="dataheader">韻鏡</th>
    <th class="dataheader" colspan=4>韻鏡</th>
    <th></th>
    <th class="dataheader">詩經</th>
    <th class="dataheader">Serica</th>
</tr>
<tr><th class="dataheader">中原音韻</th>
    <th class="dataheader"></th>
    <th class="dataheader" colspan=4></th>
    <th></th>
    <th class="dataheader"></th>
    <th class="dataheader">Recensa</th>
</tr>
<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/1">東鍾</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/1">一</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/1">東</a>
</td>
	<td><a href= "../eohan/guangyuntextbyfinal/58">董</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/113">送</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/173">屋</a></td>
<td>國風一</td>
	<td><a href = "../eohan/shijingtextbybook/1">周南一之一</td>
	<td><a href = "../eohan/gsrtextbyrhyme/1-31">1-31</a></td><td>歌</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/2">江陽</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/2">二</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/2">冬</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/59">腫</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/114">宋</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/174">沃</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/2">召南一之二</td>
	<td><a href = "../eohan/gsrtextbyrhyme/32-106">32-106</a></td><td>魚</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/3">支思</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/3">三</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/3">鍾</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/60">講</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/115">用</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/175">燭</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/3">邶一之三</td>
	<td><a href = "../eohan/gsrtextbyrhyme/107-107">107-107</a></td><td>歌</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/4">齊微</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/4">四</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/4">江</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/61">紙</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/116">絳</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/176">覺</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/4">鄘一之四</td>
	<td><a href = "../eohan/gsrtextbyrhyme/108-138">108-138</a></td><td>侯</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/5">魚模</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/5">五</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/5">支</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/62">旨</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/117">寘</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/177">質</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/5">衛一之五</td>
	<td><a href = "../eohan/gsrtextbyrhyme/139-266">139-266</a></td><td>元</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/6">皆來</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/6">六</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/6">脂</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/63">止</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/118">至</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/178">術</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/6">王一之六</td>
	<td><a href = "../eohan/gsrtextbyrhyme/267-348">267-348</a></td><td>祭月</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/7">真文</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/7">七</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/7">之</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/64">尾</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/119">志</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/179">櫛</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/7">鄭一之七</td>
	<td><a href = "../eohan/gsrtextbyrhyme/349-360">349-360</a></td><td>歌</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/8">寒山</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/8">八</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/8">微</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/65">語</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/120">未</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/180">物</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/8">齊一之八</td>
	<td><a href = "../eohan/gsrtextbyrhyme/361-392">361-392</a></td><td>真</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/9">桓歡</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/9">九</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/9">魚</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/66">麌</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/121">御</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/181">迄</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/9">魏一之九</td>
	<td><a href = "../eohan/gsrtextbyrhyme/393-415">393-415</a></td><td>質</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/10">先天</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/10">十</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/10">虞</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/67">姥</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/122">遇</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/182">月</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/10">唐一之十</td>
	<td><a href = "../eohan/gsrtextbyrhyme/416-485">416-485</a></td><td>文</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/11">蕭豪</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/11">十一</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/11">模</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/68">薺</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/123">暮</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/183">沒</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/11">秦一之十一</td>
	<td><a href = "../eohan/gsrtextbyrhyme/486-540">486-540</a></td><td>物</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/12">歌戈</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/12">十二</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/12">齊</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/69">蟹</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/124">霽</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/184">曷</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/12">陳一 之十二</td>
	<td><a href = "../eohan/gsrtextbyrhyme/541-605">541-605</a></td><td>微脂</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/13">家麻</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/13">十三</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/13">佳</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/70">駭</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/125">祭</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/185">末</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/13">檜風</td>
	<td><a href = "../eohan/gsrtextbyrhyme/606-627">606-627</a></td><td>談</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/14">車遮</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/14">十四</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/14">皆</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/71">賄</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/126">泰</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/186">黠</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/14">曹一之十四</td>
	<td><a href = "../eohan/gsrtextbyrhyme/628-642">628-642</a></td><td>盍</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/15">庚青</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/15">十五</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/15">灰</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/72">海</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/127">卦</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/187">鎋</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/15">豳一之五</td>
	<td><a href = "../eohan/gsrtextbyrhyme/643-674">643-674</a></td><td>侵</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/16">尤侯</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/16">十六</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/16">咍</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/73">軫</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/128">怪</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/188">屑</a></td>
	<td>小雅二</td>
	<td><a href = "../eohan/shijingtextbybook/16">鹿鳴之什二一</td>
	<td><a href = "../eohan/gsrtextbyrhyme/675-696">675-696</a></td><td>緝</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/17">侵尋</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/17">十七</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/17">真</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/74">準</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/129">夬</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/189">薛</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/17">彤弓之什二之三 </td>
	<td><a href = "../eohan/gsrtextbyrhyme/697-765">697-765</a></td><td>陽</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/18">監鹹</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/18">十八</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/18">諄</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/75">吻</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/130">隊</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/190">藥</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/18">祈父之什二之四</td>
	<td><a href = "../eohan/gsrtextbyrhyme/766-807">766-807</a></td><td>鐸</td></tr>
<tr><td><a href = "../eohan/zhongyuanyinyuntextbyrhyme/19">廉纖</a></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/19">十九</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/19">臻</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/76">隱</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/131">代</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/191">鐸</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/19">小旻之什二之五</td>
	<td><a href = "../eohan/gsrtextbyrhyme/808-843">808-843</a></td><td>耕</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/20">二十</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/20">文</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/77">阮</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/132">廢</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/192">陌</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/20">北山之什二之六</td>
	<td><a href = "../eohan/gsrtextbyrhyme/844-860">844-860</a></td><td>錫</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/21">二十一</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/21">殷</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/78">混</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/133">震</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/193">麥</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/21">桑扈之什二之七</td>
	<td><a href = "../eohan/gsrtextbyrhyme/861-880">861-880</a></td><td>支</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/22">二十二</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/22">元</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/79">很</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/134">稕</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/194">昔</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/22">都人士之什二之八</td>
	<td><a href = "../eohan/gsrtextbyrhyme/881-902">881-902</a></td><td>蒸</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/23">二十三</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/23">䰟</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/80">旱</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/135">問</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/195">錫</a></td>
	<td>大雅三</td>
	<td><a href = "../eohan/shijingtextbybook/23">文王之什三之一</td>
	<td><a href = "../eohan/gsrtextbyrhyme/903-935">903-935</a></td><td>職</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/24">二十四</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/24">痕</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/81">緩</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/136">焮</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/196">職</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/24">生民之什三之二</td>
	<td><a href = "../eohan/gsrtextbyrhyme/936-1001">936-1001</a></td><td>之</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/25">二十五</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/25">寒</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/82">潸</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/137">願</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/197">德</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/25">蕩之什三之三</td>
	<td><a href = "../eohan/gsrtextbyrhyme/1002-1015">1002-1015</a></td><td>冬</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/26">二十六</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/26">桓</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/83">產</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/138">慁</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/198">緝</a></td>
	<td>周頌四之一</td>
	<td><a href = "../eohan/shijingtextbybook/26">清廟之什四一之一</td>
	<td><a href = "../eohan/gsrtextbyrhyme/1016-1039">1016-1039</a></td><td>覺</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/27">二十七</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/27">刪</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/84">銑</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/139">恨</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/199">合</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/27">臣工之什四一之二</td>
	<td><a href = "../eohan/gsrtextbyrhyme/1040-1116">1040-1116</a></td><td>幽</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/28">二十八</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/28">山</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/85">獮</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/140">翰</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/200">盍</a></td>
	<td></td>
	<td><a href = "../eohan/shijingtextbybook/28">魯頌四之二</td>
	<td><a href = "../eohan/gsrtextbyrhyme/1117-1128">1117-1128</a></td><td>藥</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/29">二十九</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/29">先</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/86">篠</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/141">換</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/201">葉</a></td>
	<td></td>
	<td></td>
	<td><a href = "../eohan/gsrtextbyrhyme/1129-1171">1129-1171</a></td><td>霄(宵)</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/30">三十</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/30">仙</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/87">小</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/142">諫</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/202">帖</a></td>
	<td></td>
	<td></td>
	<td><a href = "../eohan/gsrtextbyrhyme/1172-1201">1172-1201</a></td><td>東</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/31">三十一</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/31">蕭</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/88">巧</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/143">襉</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/203">洽</a></td>
	<td></td>
	<td></td>
	<td><a href = "../eohan/gsrtextbyrhyme/1202-1228">1202-1228</a></td><td>屋</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/32">三十二</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/32">宵</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/89">晧</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/144">霰</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/204">狎</a></td>
	<td></td>
	<td></td>
	<td><a href = "../eohan/gsrtextbyrhyme/1229-1235">1229-1235</a></td><td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/33">三十三</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/33">肴</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/90">哿</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/145">線</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/205">業</a></td>
	<td></td>
	<td></td>
	<td><a href = "../eohan/gsrtextbyrhyme/1236-1261">1236-1261</a></td><td>侯</td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/34">三十四</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/34">豪</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/91">果</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/146">嘯</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/206">乏</a></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/35">三十五</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/35">歌</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/92">馬</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/147">𥬇</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/36">三十六</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/36">戈</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/93">養</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/148">效</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/37">三十七</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/37">麻</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/94">蕩</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/149">号</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/38">三十八</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/38">陽</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/95">梗</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/150">箇</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/39">三十九</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/39">唐</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/96">耿</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/151">過</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/40">四十</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/40">庚</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/97">靜</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/152">禡</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/41">四十一</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/41">耕</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/98">迥</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/153">漾</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/42">四十二</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/42">清</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/99">拯</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/154">宕</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td><a href = "../eohan/yunjingtextbyrhyme/43">四十三</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/43">青</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/100">等</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/155">映</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/44">蒸</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/101">有</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/156">諍</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/45">登</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/102">厚</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/157">勁</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/46">尤</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/103">黝</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/158">徑</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/47">侯</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/104">寑</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/159">證</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/48">幽</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/105">感</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/160">嶝</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/49">侵</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/106">敢</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/161">宥</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/50">覃</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/107">琰</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/162">𠋫</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/51">談</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/108">忝</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/163">幼</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/52">鹽</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/109">豏</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/164">沁</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/53">添</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/110">檻</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/165">勘</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/54">咸</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/111">儼</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/166">闞</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/55">銜</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/112">范</a></td>
	<td><a href= "../eohan/guangyuntextbyfinal/167">豔</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/56">嚴</a></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/168">㮇</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/57">凡</a></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/169">釅</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/170">陷</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/171">鑑</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
<tr><td></td>
	<td></td>
	<td></td>
	<td></td>
	<td><a href= "../eohan/guangyuntextbyfinal/172">梵</a></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td></tr>
</table>
</div>
<div class="bottom">
<p></p>
</div>
</div>
</div>
<div class="footer">
 <p></p>
 </div>
 </div>
<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
var sc_project=10459992; 
var sc_invisible=1; 
var sc_security="36f07708"; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><a title="shopify
analytics ecommerce" href="http://statcounter.com/shopify/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/10459992/0/36f07708/1/"
alt="shopify analytics ecommerce"></a></div></noscript>
<!-- End of StatCounter Code for Default Guide -->

</body>
</html>

